# Iteration

In [263]:
from itertools import chain
from collections.abc import Iterable, Iterator, Sized, Container, Sequence
import numpy as np
from dataclasses import dataclass

In [3]:
cities = [
    'Toulouse',
    'Grenoble',
    'Aix-en-Provence',
    'Montpellier',
]

cities2 = [
    'Bayonne',
    'Marseille',
    'Lyon',
    'Bordeaux',
]

In [4]:
# instruction for
for city in cities:
    print(city)

# expression for: list comprehension
cities_u = [ city.upper() for city in cities ]
print(cities_u)

# expression for: generator expression
length_generator = (len(city) for city in cities)
# repr: <generator object <genexpr> at 0x0000022F5D474040>
letter_count = sum(length_generator)
print(letter_count)

# same thing
letter_count = sum(len(city) for city in cities)
print(letter_count)

letter_count = sum((len(city) for city in cities), start=1000)
print(letter_count)

# expression for: dict comprehension
city_length_dict = { city: len(city) for city in cities }
print(city_length_dict) # {'Toulouse': 8, 'Grenoble': 8, 'Aix-en-Provence': 15, 'Montpellier': 11}

# enumerate:
print()
for i, city in enumerate(cities):
    print(f"#{i}# {city}")

print()
for i, city in enumerate(cities, start=1):
    print(f"#{i}# {city}")

# ! avoid index indirection:
print()
for i in range(len(cities)):
    print(f"#{i}# {cities[i]}")

# iterate with zip
print()
for city, n, letter in zip(cities, range(1,1000), 'abcdefghijklmnopqrstuvwxyz'):
    print(f"#{city}#{n}#{letter}")

# chain of iterables (module itertools)
print()
for city in chain(cities, cities2):
    print(city)

# Recap: builtin functions with arg iterable
# list, tuple, dict
# map, filter
# sum, min, max
# any, all
# enumerate, zip, 
# reversed, sorted
# iter (-> iterator)
print()
print(
    "are all city lengths > 5:",
    all(len(city) > 5 for city in cities)
)
print(
    "is any city with length > 10",
    any(len(city) > 10 for city in cities)
)

print()
city_d = dict([
    ('name', 'Toulouse'),
    ('population', 477_000),
    ('zipcode', '31000')
])
print(city_d)

city_d = dict(
    name='Toulouse',
    population=477_000,
    zipcode='31000'
)
print(city_d)
# {'name': 'Toulouse', 'population': 477000, 'zipcode': '31000'}

Toulouse
Grenoble
Aix-en-Provence
Montpellier
['TOULOUSE', 'GRENOBLE', 'AIX-EN-PROVENCE', 'MONTPELLIER']
42
42
1042
{'Toulouse': 8, 'Grenoble': 8, 'Aix-en-Provence': 15, 'Montpellier': 11}

#0# Toulouse
#1# Grenoble
#2# Aix-en-Provence
#3# Montpellier

#1# Toulouse
#2# Grenoble
#3# Aix-en-Provence
#4# Montpellier

#0# Toulouse
#1# Grenoble
#2# Aix-en-Provence
#3# Montpellier

#Toulouse#1#a
#Grenoble#2#b
#Aix-en-Provence#3#c
#Montpellier#4#d

Toulouse
Grenoble
Aix-en-Provence
Montpellier
Bayonne
Marseille
Lyon
Bordeaux

are all city lengths > 5: True
is any city with length > 10 True

{'name': 'Toulouse', 'population': 477000, 'zipcode': '31000'}
{'name': 'Toulouse', 'population': 477000, 'zipcode': '31000'}


In [5]:
it = iter(cities)
it

In [6]:
# evaluate this cell until exception StopIteration is raised
next(it)

'Toulouse'

In [7]:
it = iter(cities)
while True:
    try:
        city = next(it)
        print(city)
    except StopIteration:
        break

Toulouse
Grenoble
Aix-en-Provence
Montpellier


In [8]:
it = iter(cities)
it

In [9]:
it2 = iter(it)
it2

In [10]:
assert it is it2

In [11]:
it = iter(cities)
next(it) # advance once
list(zip(cities, it))

[('Toulouse', 'Grenoble'),
 ('Grenoble', 'Aix-en-Provence'),
 ('Aix-en-Provence', 'Montpellier')]

In [12]:
list(zip(cities, (city.upper() for city in cities)))

[('Toulouse', 'TOULOUSE'),
 ('Grenoble', 'GRENOBLE'),
 ('Aix-en-Provence', 'AIX-EN-PROVENCE'),
 ('Montpellier', 'MONTPELLIER')]

In [13]:
# what is the iterator of a genarator ?
g = (city.upper() for city in cities)
g

<generator object <genexpr> at 0x000001B6C9661BE0>

In [14]:
it = iter(g)
it

<generator object <genexpr> at 0x000001B6C9661BE0>

In [15]:
assert g is it

In [16]:
next(g)

'TOULOUSE'

In [17]:
list(g)

['GRENOBLE', 'AIX-EN-PROVENCE', 'MONTPELLIER']

In [18]:
def generate_inf(value):
    while True:
        yield value

In [19]:
g = generate_inf(1)
for _ in range(11):
    print(next(g))

1
1
1
1
1
1
1
1
1
1
1


In [38]:
def generate_123():
    yield 1
    yield 2
    yield 3

In [40]:
generate_123()

<generator object generate_123 at 0x000001B6C96790C0>

In [42]:
for v in generate_123():
    print(v)

1
2
3


In [44]:
sum(generate_123())

6

## Exercise: generate numbers of Fibonacci sequence: 0 1 1 2 3 5 8 13 ...
- version 1: infinite generator
- version 2: limited to n values

In [49]:
def fibonacci():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a + b

In [55]:
g = fibonacci()
values = [next(g) for _ in range(10)] # 10 first values
values

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [57]:
[next(g) for _ in range(10)]

[55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]

In [59]:
[next(g) for _ in range(10)]

[6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229]

In [61]:
type(fibonacci)

function

In [65]:
type(fibonacci())

generator

In [247]:
def fibonacci_n(n):
    """yields n first numbers of Fibonnaci sequence (starting with 0)

    arguments:
    - n: limit the number of generated values to n
    """
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b

In [249]:
fibonacci_n?

Signature: fibonacci_n(n)
Docstring:
yields n first numbers of Fibonnaci sequence (starting with 0)

arguments:
- n: limit the number of generated values to n
File:      c:\users\matth\appdata\local\temp\ipykernel_6104\432662187.py
Type:      function

In [251]:
fibonacci_n.__doc__

'yields n first numbers of Fibonnaci sequence (starting with 0)\n\n    arguments:\n    - n: limit the number of generated values to n\n    '

In [53]:
values = list(fibonacci_n(10))
values

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [73]:
# an iterable object has '__iter__' method
cities.__iter__

<method-wrapper '__iter__' of list object at 0x000001B6C9681100>

In [75]:
# an iterator object has '__next__' and '__iter__' method 
it = iter(cities)
it.__next__

<method-wrapper '__next__' of list_iterator object at 0x000001B6CCF66C50>

In [71]:
it.__iter__

<method-wrapper '__iter__' of list_iterator object at 0x000001B6CCFD3FD0>

In [89]:
assert isinstance(cities, Iterable)
assert not isinstance(cities, Iterator)

In [85]:
assert isinstance(it, Iterator)
assert isinstance(it, Iterable)

In [91]:
g = fibonacci_n(10)
assert isinstance(g, Iterator)
assert isinstance(g, Iterable)

In [95]:
# a list is Iterable + ....
assert isinstance(cities, Iterable)
assert isinstance(cities, Sized)
assert isinstance(cities, Container)
assert isinstance(cities, Sequence)

In [1]:
def fixture_with_setup_teardown():
    print('setup')
    yield 123
    print('teardown')

In [11]:
g = fixture_with_setup_teardown()

In [13]:
param = next(g)

setup


In [15]:
#use param
print(param)

123


In [17]:
try: 
    next(g)
except StopIteration:
    pass

teardown


## Méthodes d'implémentation
- builtins:
    - len: `__len__`
    - repr: `__repr__`
    - str: `__str__`
    - iter: `__iter__`
    - next: `__next__`
    - bool: `__bool__` (truthness of an object)
- operators:
    - ==, != : `__eq__`, `__ne__`
    - <, <=, >, >= : `__lt__`, `__le__` , `__gt__` , `__ge__`,
    - `+` : `__add__`, `__radd__` (idem: -, *, /, //, **, %, @)
    - += : `__iadd__` (idem: -=, *=, /=, //=, %= , **=, @=)
    - in : `__contains__`
- instance, class
    - constructor: `__init__` (just after `__new__`)
    - type: `__class__` (attribute)
    - docstring (IDE, help, ?): `__doc__` (attribute)
    - dictionnary: __dict__`

In [261]:
a.__dict__

{}

In [267]:
@dataclass
class City:
    name: str
    population: int

c = City('Toulouse', 477_000)
c.__dict__

{'name': 'Toulouse', 'population': 477000}

In [ ]:
x.__init__

In [236]:
sorted([4, 7, 12, 23, 90]) # call < (__lt__) of type 'int'

[4, 7, 12, 23, 90]

In [240]:
a1 = A()
a2 = A()
## TypeError: '<' not supported between instances of 'A' and 'A'
# sorted([a1, a2])

In [244]:
# all objects have defaults: lt, le, gt, ge returning NotImplemented
a1.__lt__(a2)

NotImplemented

In [231]:
12 == "ceci n'est pas un nombre" 

False

In [217]:
city = 'Toulouse'

In [221]:
## TypeError: 'str' object does not support item assignment
#city[0] = 'B'

In [225]:
city += ', ville rose' # new object (no __iadd__ in type str)
city

'Toulouse, ville rose, ville rose'

In [ ]:
city.__i

In [185]:
7 / 3,  7 // 3,   7 % 3 # calls resp.  __truediv__, __floordiv__, __mod__

(2.3333333333333335, 2, 1)

In [193]:
nb = 7
# nb.__divmod__(3)
divmod(7, 3)

(2, 1)

In [197]:
# look for methods containing 'div' in object x (ndarray)
[method for method in dir(x) if 'div' in method]

['__divmod__',
 '__floordiv__',
 '__ifloordiv__',
 '__itruediv__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rtruediv__',
 '__truediv__']

In [154]:
cities + cities

['Toulouse',
 'Grenoble',
 'Aix-en-Provence',
 'Montpellier',
 'Toulouse',
 'Grenoble',
 'Aix-en-Provence',
 'Montpellier']

In [158]:
cities += ['Pau', 'Lille']

In [203]:
# call + on types 'str' and 'int' => str.__add__
'oh' * 5

'ohohohohoh'

In [205]:
# call + on types 'int' and 'str' 
# => int.__add__: answer NotImplemented
# => str.__radd__ => answer 'ohohoh'
5 * 'oh'

'ohohohohoh'

In [207]:
nb = 5
nb.__add__('oh')

NotImplemented

In [211]:
x + 1

array([ 1.        ,  1.00012566,  1.00025133, ..., 13.56611928,
       13.56624495, 13.56637061])

In [213]:
1 + x

array([ 1.        ,  1.00012566,  1.00025133, ..., 13.56611928,
       13.56624495, 13.56637061])

In [165]:
## TypeError: unsupported operand type(s) for -: 'list' and 'list'
#cities - cities

In [167]:
cities * 3

['Toulouse',
 'Grenoble',
 'Aix-en-Provence',
 'Montpellier',
 'Pau',
 'Lille',
 'Toulouse',
 'Grenoble',
 'Aix-en-Provence',
 'Montpellier',
 'Pau',
 'Lille',
 'Toulouse',
 'Grenoble',
 'Aix-en-Provence',
 'Montpellier',
 'Pau',
 'Lille']

In [171]:
## TypeError: can't multiply sequence by non-int of type 'list'
#cities * cities

In [106]:
print(repr(cities))
print(str(cities))

['Toulouse', 'Grenoble', 'Aix-en-Provence', 'Montpellier']
['Toulouse', 'Grenoble', 'Aix-en-Provence', 'Montpellier']


In [114]:
x = np.linspace(0, 4*np.pi, 100_000)
print(repr(x))
print(str(x))

array([0.00000000e+00, 1.25664963e-04, 2.51329926e-04, ...,
       1.25661193e+01, 1.25662449e+01, 1.25663706e+01])
[0.00000000e+00 1.25664963e-04 2.51329926e-04 ... 1.25661193e+01
 1.25662449e+01 1.25663706e+01]


In [118]:
print(x) # calls str
x # calls repr

[0.00000000e+00 1.25664963e-04 2.51329926e-04 ... 1.25661193e+01
 1.25662449e+01 1.25663706e+01]


array([0.00000000e+00, 1.25664963e-04, 2.51329926e-04, ...,
       1.25661193e+01, 1.25662449e+01, 1.25663706e+01])

In [126]:
print(f" * repr x = {x!r},\n\n * str x = {x}")

 * repr x = array([0.00000000e+00, 1.25664963e-04, 2.51329926e-04, ...,
       1.25661193e+01, 1.25662449e+01, 1.25663706e+01]),

 * str x = [0.00000000e+00 1.25664963e-04 2.51329926e-04 ... 1.25661193e+01
 1.25662449e+01 1.25663706e+01]


In [128]:
city = "Toulouse"
city

'Toulouse'

In [130]:
print(str(city))
print(repr(city))

Toulouse
'Toulouse'


In [132]:
class A:
    pass

a = A()
print(str(a))
print(repr(a))

In [151]:
# truthness
for o in '', 'python', [], [1, 2,3], None, 0, 1, a:
    print(repr(o), ':', bool(o))
    if o:
        print(repr(o), ' is  true') 
    print()

'' : False

'python' : True
'python'  is  true

[] : False

[1, 2, 3] : True
[1, 2, 3]  is  true

None : False

0 : False

1 : True
1  is  true

<__main__.A object at 0x000001B6CC2144D0> : True
<__main__.A object at 0x000001B6CC2144D0>  is  true



In [ ]:
x.__